# Generated by Django 3.0.3 on 2020-04-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_name',
        ),
    ]
