# Generated by Django 3.0.3 on 2020-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200402_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default='some value', max_length=240, unique='True'),
        ),
    ]
