# Generated by Django 3.0.3 on 2020-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_topic_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=240)),
                ('topic_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='topic',
        ),
        migrations.RemoveField(
            model_name='webpages',
            name='page_address',
        ),
        migrations.RemoveField(
            model_name='webpages',
            name='page_name',
        ),
        migrations.AddField(
            model_name='webpages',
            name='address',
            field=models.URLField(default='def value'),
        ),
    ]
