# Generated by Django 3.0.3 on 2020-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20200402_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='webpages',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topic_date',
        ),
        migrations.AddField(
            model_name='topics',
            name='topic_email',
            field=models.EmailField(default='def', max_length=254),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_name',
            field=models.CharField(default='def', max_length=240),
        ),
    ]
